main/urls.py
from django.urls import path, include

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('category/<slug:slug>/', views.SpecificProductCategory.as_view(), name="view_for_category"),
    path('orders/', include('customer_orders.urls', namespace='orders'))
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUserFormViews.as_view(), name='register'),
    path('cart/', include('shopping_cart.urls', namespace='shopping_cart'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.urls import path

from shopping_cart import views

app_name = 'shopping_cart'

urlpatterns = [
    path('', views.Cart.as_view(), name='shopping_cart_detail'),
    path('add/<int:product_id>/', views.Cart.as_view(), name='shopping_cart_add'),
    path('remove/<int:product_id>/', views.Cart.cart_remove, name='cart_remove')
]

shopping_cart/models.py
from django.db import models

# Create your models here.

shopping_cart/forms/forms.py
from django import forms

AMOUNT_PRODUCT = [(i, str(i)) for i in range(1, 10)]


class AmountProductInCart(forms.Form):
    amount = forms.TypedChoiceField(choices=AMOUNT_PRODUCT, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shopping_cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from main.models import ProductShop, CategoryProduct
from shopping_cart.forms.forms import AmountProductInCart
from shopping_cart.shopping_cart import ShoppingCart


class Cart(View):
    category_product = CategoryProduct.get_all_category()

    def post(self, request, product_id):
        cart = ShoppingCart(request)
        product = get_object_or_404(ProductShop, id=product_id)
        form = AmountProductInCart(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add_product_to_shopping_cart(product, cd['amount'], cd['update'])
        else:
            print('error')
        return redirect('shopping_cart:shopping_cart_detail')

    def get(self, request, *args, **kwargs):
        cart = ShoppingCart(request)
        for item in cart:
            item['update_amount_form'] = AmountProductInCart(initial={'amount': item['amount'], 'update': True})
        return render(request, 'cart/detail.html', {'cart': cart, 'category_product': self.category_product})

    def cart_remove(request, product_id):
        cart = ShoppingCart(request)
        product = get_object_or_404(ProductShop, id=product_id)
        cart.remove_product_with_shopping_cart(product)
        return HttpResponseRedirect(reverse('shopping_cart:shopping_cart_detail'))

shopping_cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %} Zakupoholik.pl {% endblock %}
{% block content %}
    <ul>

        {% for item in cart %}
            {% with product=item.product_shop %}
                <div id="element_in_cart">
                    <p>{{ product }}</p>
                    <p id="delete"><a href="{% url 'shopping_cart:cart_remove' product.id %}">Usuń</a></p>
                    <p>Cena jednostkowa {{ item.price }}</p>
                    <p>Cena całkowita {{ item.total_price }}</p>
                    <p id="amount">ilość</p>
                    <form action="{% url 'shopping_cart:shopping_cart_add' product.id %}" method="post">
                        {{ item.update_amount_form.amount }}
                        {{ item.update_amount_form.update }}
                        <input type="submit" value="Zmień">
                        {% csrf_token %}
                    </form>

                </div>
            {% endwith %}
        {% endfor %}
        {% if user.is_authenticated %}
            {% if cart|length > 0 %}
                <a href="{% url 'main:customer_orders:order_create' %}" id="pay">Zapłać</a>
            {% else %}
                <p>Koszyk jest pusty</p>
            {% endif %}
        {% else %}
            <a href="{% url 'login' %}" id="pay">Zapłać</a>
        {% endif %}
    </ul>
{% endblock %}