dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('first/', views.FirstDimensionDashboard.as_view(), name='first_dimension'),
    path('second/', views.SecondDimensionDashboard.as_view(), name='second_dimension'),
    path('third/', views.ThirdDimensionDashboard.as_view(), name='third_dimension'),
]

main/urls.py
from django.urls import path, include

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('category/<slug:slug>/', views.SpecificProductCategory.as_view(), name="view_for_category"),
    path('orders/', include('customer_orders.urls', namespace='orders'))
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUserFormViews.as_view(), name='register'),
    path('cart/', include('shopping_cart.urls', namespace='shopping_cart'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.urls import path

from shopping_cart import views

app_name = 'shopping_cart'

urlpatterns = [
    path('', views.Cart.as_view(), name='shopping_cart_detail'),
    path('add/<int:product_id>/', views.Cart.as_view(), name='shopping_cart_add'),
    path('remove/<int:product_id>/', views.Cart.cart_remove, name='cart_remove')
]

dashboard/models.py
from django.db import models


class Data(models.Model):
    id = models.AutoField(primary_key=True)
    month = models.CharField(max_length=40)
    quarter = models.CharField(max_length=40)
    year = models.CharField(max_length=40)


class CategoryProduct(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)


class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name_product = models.CharField(max_length=80)
    id_category_product = models.ForeignKey(CategoryProduct, on_delete=models.CASCADE)
    amount = models.IntegerField(default=1)
    price_product = models.DecimalField(max_digits=7, decimal_places=2)


class Client(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    surname = models.CharField(max_length=40)
    zip_code = models.CharField(max_length=8)


class Sales(models.Model):
    id_client = models.ForeignKey(Client, on_delete=models.CASCADE)
    id_data = models.ForeignKey(Data, on_delete=models.CASCADE)
    id_product = models.ManyToManyField(Product)
    total_price = models.DecimalField(max_digits=8, decimal_places=2)

dashboard/views.py
from django.shortcuts import redirect
from django.views.generic import ListView
from customer_orders.models import CustomerOrder, ElementInCustomerOrder
from dashboard.data_warehouse import DataWarehouse
from dashboard.models import Sales
from main.models import CategoryProduct


class DashboardView(ListView):
    template_name = 'dashboard.html'

    model = CategoryProduct
    orders = CustomerOrder.get_all_orders()

    def post(self, request):
        not_archived = [self.__create_object_order(order, archived=True) for order in
                        CustomerOrder.get_all_not_archived_orders()]

        [self.__archive_data(element) for element in not_archived]
        return redirect('dashboard:dashboard')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_orders'] = self.__get_list_orders()
        return context

    def __count_the_order_amount(self, elements):
        total_price = 0
        for element in elements:
            total_price = element.price_product * element.amount
        return total_price

    def __create_object_order(self, order, archived=False):
        elements = ElementInCustomerOrder.get_all_element_in_order(order.id)
        total_price = self.__count_the_order_amount(elements)
        obj = {
            "id": order.id,
            "create_date_day": f'{order.create_date.date().day}',
            "create_date_month": f'{order.create_date.date().month}',
            "create_date_year": f'{order.create_date.date().year}',
            "name_customer": order.customer_first_name,
            "customer_last_name": order.customer_last_name,
            "zip_code": order.zip_code,
            "archived": order.archived,
            "products": elements,
            "total_price": total_price
        }
        if archived:
            el = CustomerOrder.objects.filter(id=order.id).first()
            el.archived = True
            el.save()
        return obj

    def __get_list_orders(self):
        orders = [self.__create_object_order(order) for order in self.orders]
        return orders

    def __archive_data(self, element):
        try:
            DataWarehouse.create_sales(
                id_data=DataWarehouse.create_data_object(element),
                id_product=DataWarehouse.create_product_with_category(element),
                id_client=DataWarehouse.create_client(element),
                total_price=element['total_price']
            )
        except:
            print('Coś poszło nie tak, obiekt nie został stworzony')


class FirstDimensionDashboard(ListView):
    template_name = 'first_dashboard.html'
    model = Sales

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_orders'] = self.__get_sales_after_year()
        return context

    def __get_elements_only_this_year(self, el):
        if el.id_data.year == '2023':
            return el

    def __get_sales_after_year(self):
        list_elements = [self.__get_elements_only_this_year(el) for el in self.model.objects.all()]
        return list_elements


class SecondDimensionDashboard(ListView):
    template_name = 'second_dashboard.html'
    model = Sales

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_orders'] = self.__get_sales_after_second_quarter()
        return context

    def __get_elements_after_zip_code(self, el):
        if el.id_client.zip_code == '12-1234':
            return el

    def __get_sales_after_second_quarter(self):
        list_elements = [self.__get_elements_after_zip_code(el) for el in self.model.objects.all()]
        return list_elements


class ThirdDimensionDashboard(ListView):
    template_name = 'third_dashboard.html'
    model = Sales

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_orders'] = self.__get_sales_after_total_price()
        return context

    def __get_elements_only_larger_than_three_thousand_zlotys(self, el):
        if el.total_price > 100:
            return el

    def __get_sales_after_total_price(self):
        list_elements = [self.__get_elements_only_larger_than_three_thousand_zlotys(el) for el in
                         self.model.objects.all()]
        return list_elements

dashboard/templates/dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
<div class="wrapper-main">
    <header>
        <div class="img">
            <img src="{% static 'img/logo.jpg' %}" alt="logo">
        </div>
        <div class="searcher">
            <div class="search-border">
                <input type="text" name="searcher">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
        </div>
        <div class="user_menu">
            {% if user.is_superuser %}
                <a href="{% url 'main:main' %}" id="dashboard">Opuść</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a class="login" href="{% url 'logout' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>{{ user.username }}</p>
                </a>
            {% else %}
                <a class="login" href="{% url 'login' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>Zaloguj</p>
                </a>
            {% endif %}
            <div class="cart">
                <a href="{% url 'shopping_cart:shopping_cart_detail' %}">
                    <img src="{% static 'img/cart-shopping.svg' %}" alt="cart">
                </a>
            </div>
        </div>
    </header>
    <div class="content-wrap">
        <nav id="data_warehouse_menu">
            <ul>
                <li>
                    <a href="{% url 'dashboard:first_dimension' %}">Pierwszy wymiar</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:second_dimension' %}">Drugi wymiar</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:third_dimension' %}">Trzeci wymiar</a>
                </li>
            </ul>
        </nav>
        <div class="content">
            <h3>Strona główna. Info.</h3>
            <form action="" method="post">
                {% csrf_token %}
                <button>Zasil hurtownie danych</button>
            </form>
            <div class="orders_list">
                <table>
                    <tr>
                        <th class="small">id</th>
                        <th class="small">Dzień zamówienia</th>
                        <th class="small">Miesiąc zamówienia</th>
                        <th>Rok zamówienia</th>
                        <th>Imię klienta</th>
                        <th>Nazwisko klienta</th>
                        <th>Kod pocztowy</th>
                        <th>Produkty</th>
                        <th>Cena końcowa</th>
                        <th>Zaarchiwizowane</th>
                    </tr>
                    {% for order in all_orders %}
                        <tr class="{% if order.id|divisibleby:2 %}even{% else %}odd{% endif %}">
                            <td>{{ order.id }}</td>
                            <td>{{ order.create_date_day }}</td>
                            <td>{{ order.create_date_month }}</td>
                            <td>{{ order.create_date_year }}</td>
                            <td>{{ order.name_customer }}</td>
                            <td>{{ order.customer_last_name }}</td>
                            <td>{{ order.zip_code }}</td>
                            <td>
                                {% for product in order.products %}
                                    {{ product.product.name_product }} <br>
                                {% endfor %}
                            </td>
                            <td>{{ order.total_price }}</td>
                            <td>{{ order.archived }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
</body>
</html>

dashboard/templates/first_dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
<div class="wrapper-main">
    <header>
        <div class="img">
            <img src="{% static 'img/logo.jpg' %}" alt="logo">
        </div>
        <div class="searcher">
            <div class="search-border">
                <input type="text" name="searcher">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
        </div>
        <div class="user_menu">
            {% if user.is_superuser %}
                <a href="{% url 'main:main' %}" id="dashboard">Opuść</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a class="login" href="{% url 'logout' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>{{ user.username }}</p>
                </a>
            {% else %}
                <a class="login" href="{% url 'login' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>Zaloguj</p>
                </a>
            {% endif %}
            <div class="cart">
                <a href="{% url 'shopping_cart:shopping_cart_detail' %}">
                    <img src="{% static 'img/cart-shopping.svg' %}" alt="cart">
                </a>
            </div>
        </div>
    </header>
    <div class="content-wrap">
        <nav id="data_warehouse_menu">
            <ul>
                <li>
                    <a href="{% url 'dashboard:first_dimension' %}">Pierwszy wymiar</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:second_dimension' %}">Drugi wymiar</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:third_dimension' %}">Trzeci wymiar</a>
                </li>
            </ul>
        </nav>
        <div class="content">
            <h3>Pierwszy wymiar - Zamówienia dla roku 2023.</h3>
            <div class="orders_list">
                <table>
                    <tr>
                        <th class="small">id</th>
                        <th class="small">Miesiąc zamówienia</th>
                        <th class="small">Kwartał zamówienia</th>
                        <th>Imię klienta</th>
                        <th>Nazwisko klienta</th>
                        <th>Kod pocztowy</th>
                        <th>Produkty</th>
                        <th>Cena końcowa</th>
                    </tr>
                    {% for order in all_orders %}
                        <tr class="{% if order.id|divisibleby:2 %}even{% else %}odd{% endif %}">
                            <td>{{ order.id }}</td>
                        <td>{{ order.id_data.month }}</td>
                        <td>{{ order.id_data.quarter }}</td>
                            <td>{{ order.id_client.name }}</td>
                            <td>{{ order.id_client.surname }}</td>
                            <td>{{ order.id_client.zip_code }}</td>
                            <td>
                                {% for product in order.id_product.all %}
                                    {{ product.name_product }} <br>
                                {% endfor %}
                            </td>
                            <td>{{ order.total_price }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
</body>
</html>

dashboard/templates/second_dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
<div class="wrapper-main">
    <header>
        <div class="img">
            <img src="{% static 'img/logo.jpg' %}" alt="logo">
        </div>
        <div class="searcher">
            <div class="search-border">
                <input type="text" name="searcher">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
        </div>
        <div class="user_menu">
            {% if user.is_superuser %}
                <a href="{% url 'main:main' %}" id="dashboard">Opuść</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a class="login" href="{% url 'logout' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>{{ user.username }}</p>
                </a>
            {% else %}
                <a class="login" href="{% url 'login' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>Zaloguj</p>
                </a>
            {% endif %}
            <div class="cart">
                <a href="{% url 'shopping_cart:shopping_cart_detail' %}">
                    <img src="{% static 'img/cart-shopping.svg' %}" alt="cart">
                </a>
            </div>
        </div>
    </header>
    <div class="content-wrap">
        <nav id="data_warehouse_menu">
            <ul>
                <li>
                    <a href="{% url 'dashboard:first_dimension' %}">Pierwszy wymiar</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:second_dimension' %}">Drugi wymiar</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:third_dimension' %}">Trzeci wymiar</a>
                </li>
            </ul>
        </nav>
        <div class="content">
            <h3>Drugi wymiar - Dane dla danego kodu pocztowego "12-1234"</h3>
            <div class="orders_list">
                <table>
                    <tr>
                        <th class="small">id</th>
                        <th>Kod pocztowy</th>
                        <th>Imię klienta</th>
                        <th>Nazwisko klienta</th>
                        <th>Produkty</th>
                        <th>Cena końcowa</th>
                    </tr>
                    {% for order in all_orders %}
                        {% if order.id != None %}
                            <tr class="{% if order.id|divisibleby:2 %}even{% else %}odd{% endif %}">
                                <td>{{ order.id }}</td>
                                <td>{{ order.id_client.zip_code }}</td>
                                <td>{{ order.id_client.name }}</td>
                                <td>{{ order.id_client.surname }}</td>

                                <td>
                                    {% for product in order.id_product.all %}
                                        {{ product.name_product }} <br>
                                    {% endfor %}
                                </td>
                                <td>{{ order.total_price }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
</body>
</html>

dashboard/templates/third_dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
<div class="wrapper-main">
    <header>
        <div class="img">
            <img src="{% static 'img/logo.jpg' %}" alt="logo">
        </div>
        <div class="searcher">
            <div class="search-border">
                <input type="text" name="searcher">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
        </div>
        <div class="user_menu">
            {% if user.is_superuser %}
                <a href="{% url 'main:main' %}" id="dashboard">Opuść</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a class="login" href="{% url 'logout' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>{{ user.username }}</p>
                </a>
            {% else %}
                <a class="login" href="{% url 'login' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>Zaloguj</p>
                </a>
            {% endif %}
            <div class="cart">
                <a href="{% url 'shopping_cart:shopping_cart_detail' %}">
                    <img src="{% static 'img/cart-shopping.svg' %}" alt="cart">
                </a>
            </div>
        </div>
    </header>
    <div class="content-wrap">
        <nav id="data_warehouse_menu">
            <ul>
                <li>
                    <a href="{% url 'dashboard:first_dimension' %}">Pierwszy wymiar</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:second_dimension' %}">Drugi wymiar</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:third_dimension' %}">Trzeci wymiar</a>
                </li>
            </ul>
        </nav>
        <div class="content">
            <h3>Trzeci wymiar - Dane dla kwot powyżej 100zł</h3>
            <div class="orders_list">
                <table>
                    <tr>
                        <th class="small">id</th>
                        <th class="small">Miesiąc zamówienia</th>
                        <th class="small">Kwartał zamówienia</th>
                        <th>Imię klienta</th>
                        <th>Nazwisko klienta</th>
                        <th>Kod pocztowy</th>
                        <th>Produkty</th>
                        <th>Cena końcowa</th>
                    </tr>
                    {% for order in all_orders %}
                        <tr class="{% if order.id|divisibleby:2  %}even{% else %}odd{% endif %}">
                            <td>{{ order.id }}</td>
                            <td>{{ order.id_data.month }}</td>
                            <td>{{ order.id_data.quarter }}</td>
                            <td>{{ order.id_client.name }}</td>
                            <td>{{ order.id_client.surname }}</td>
                            <td>{{ order.id_client.zip_code }}</td>
                            <td>
                                {% for product in order.id_product.all %}
                                    {{ product.name_product }} <br>
                                {% endfor %}
                            </td>
                            <td>{{ order.total_price }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
</body>
</html>