dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('first/', views.FirstDimensionDashboard.as_view(), name='first_dimension'),
    path('second/', views.SecondDimensionDashboard.as_view(), name='second_dimension'),
    path('third/', views.ThirdDimensionDashboard.as_view(), name='third_dimension'),
]

main/urls.py
from django.urls import path, include

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('category/<slug:slug>/', views.SpecificProductCategory.as_view(), name="view_for_category"),
    path('orders/', include('customer_orders.urls', namespace='orders'))
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUserFormViews.as_view(), name='register'),
    path('cart/', include('shopping_cart.urls', namespace='shopping_cart'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.urls import path

from shopping_cart import views

app_name = 'shopping_cart'

urlpatterns = [
    path('', views.Cart.as_view(), name='shopping_cart_detail'),
    path('add/<int:product_id>/', views.Cart.as_view(), name='shopping_cart_add'),
    path('remove/<int:product_id>/', views.Cart.cart_remove, name='cart_remove')
]

main/models.py
from django.db import models


class CategoryProduct(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=30)
    descriptions = models.TextField()
    font_category = models.CharField(max_length=40)

    def __str__(self):
        return self.name

    @classmethod
    def get_all_category(cls):
        return cls.objects.all()

    @classmethod
    def get_category_after_slug(cls,slug):
        return cls.objects.filter(slug=slug)

    @classmethod
    def get_category_after_name(cls, name: str):
        return cls.objects.filter(name=name)

    @classmethod
    def get_id_category_after_slug(cls, slug):
        return cls.objects.filter(slug=slug).first().id

    @classmethod
    def get_name_category_after_id(cls, id):
        return cls.objects.filter(id__in=id).first().name


class ProductShop(models.Model):
    category_product = models.ForeignKey(CategoryProduct, on_delete=models.CASCADE)
    name_product = models.CharField(max_length=40, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    descriptions = models.TextField()
    average_grade = models.DecimalField(max_digits=2, decimal_places=1, default=5)
    image_product = models.ImageField(upload_to='media/image_product/%Y/%m%d')
    price = models.DecimalField(max_digits=6, decimal_places=2)
    promotion = models.BooleanField(default=False)
    available_product = models.BooleanField(default=True)

    class Meta:
        index_together = ('id', 'slug')

    def __str__(self):
        return self.name_product

    @classmethod
    def get_highest_rated_products(cls):
        return cls.objects.all().order_by('-average_grade')[:10]

    @classmethod
    def get_all_products(cls):
        return cls.objects.all()

    @classmethod
    def get_product_after_id(cls,id_product: object):
        return cls.objects.filter(id__in=id_product)

    @classmethod
    def get_products_after_name(cls, name_product: str):
        return cls.objects.filter(name_product=name_product)

    @classmethod
    def get_all_products_with_promotion(cls):
        return cls.objects.filter(promotion=True)

    @classmethod
    def get_product_after_category(cls, name):
        return cls.objects.filter(category_product=name)

    @classmethod
    def get_products_with_category_after_slug(cls, slug):
        name = CategoryProduct.get_id_category_after_slug(slug)
        return cls.get_product_after_category(name)

main/forms/register_form.py
from django import forms
from django.contrib.auth.models import User


class RegisterFormNewUser(forms.ModelForm):
    username = forms.CharField(label="Login:",
                               max_length=20,
                               widget=forms.TextInput(attrs={'id': 'username_register', }))
    email = forms.EmailField(label="Email:",
                             widget=forms.TextInput(attrs={'id': 'email_register'}))
    password = forms.CharField(label='Hasło:',
                               widget=forms.PasswordInput(attrs={'id': 'password_register'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

main/views.py
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView

from main.chatbot.chatbot import ChatBot
from main.forms.register_form import RegisterFormNewUser
from main.models import CategoryProduct, ProductShop
from shopping_cart.forms.forms import AmountProductInCart


class MainView(ListView):
    template_name = 'index.html'
    model = CategoryProduct
    form = AmountProductInCart()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_product'] = self.model.get_all_category()
        context['all_products_with_promotion'] = ProductShop.get_all_products_with_promotion()
        context['form'] = self.form
        return context

    def post(self, request):
        print(request.POST.get('user_question'))
        the_question = request.POST.get('user_question')

        response = ChatBot().chatbot_response(the_question)
        return JsonResponse({'response': response})


class SpecificProductCategory(DetailView):
    template_name = 'detail_category.html'
    model = CategoryProduct

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_product'] = CategoryProduct.objects.all()
        context['form'] = AmountProductInCart()
        context['product_with_category'] = ProductShop.get_products_with_category_after_slug(slug=self.kwargs['slug'])
        return context


class RegisterUserFormViews(View):
    """Rejestracja użytkownika. """
    form_class = RegisterFormNewUser
    template_name = 'registration/register.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('../')

        return render(request, self.template_name, {'form': form})

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Zakupoholik</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/chatbot.css' %}">
</head>
<body>
<div class="wrapper-main">
    <header>
        <div class="img">
            <img src="{% static 'img/logo.jpg' %}" alt="logo">
        </div>
        <div class="searcher">
            <div class="search-border">
                <input type="text" name="searcher">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
        </div>
        <div class="user_menu">
        {% if user.is_superuser %}
            <a href="{% url 'dashboard:dashboard' %}" id="dashboard">dashboard</a>
        {% endif %}
            {% if user.is_authenticated %}
                <a class="login" href="{% url 'logout' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>{{ user.username }}</p>
                </a>
            {% else %}
                <a class="login" href="{% url 'login' %}">
                    <img src="{% static 'img/user.svg' %}" alt="user">
                    <p>Zaloguj</p>
                </a>
            {% endif %}
            <div class="cart">
                <a href="{% url 'shopping_cart:shopping_cart_detail' %}">
                    <img src="{% static 'img/cart-shopping.svg' %}" alt="cart">
                </a>
            </div>
        </div>
    </header>
    <nav>
        <ul>
            {% for category in category_product %}
                <li><a href="{% url 'main:view_for_category'  category.slug %}">{{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>
    <div class="main_image_page">
        <img src="{% static 'img/promka.jpg' %}" alt="promocja baner">
    </div>

    {% block content %}
    {% endblock %}

    <div id="chatbot">
        <img src="{% static 'img/chat.png' %}" alt="" onclick="openChatWindow()">
    </div>
    <div id="bot">
        <div id="label_mssg"><i class="fa-regular fa-circle-xmark" onclick="closeChatWindow()"></i></div>
        <div id="conversation"></div>
        <form action="" method="post" onsubmit="handle_conversation_with_bot(event)">
            <input type="text" name="question" id="user_question">
            <button>Klik</button>
            {% csrf_token %}
        </form>
    </div>
</div>
<footer>Sebastian Jadczak</footer>
</body>
<script src="https://kit.fontawesome.com/0d0608dae7.js" crossorigin="anonymous"></script>
<script src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/handle_chatbot.js' %}"></script>
<script src="{% static 'js/jquery-3.6.4.js' %}"></script>
</html>

main/templates/detail_category.html
{% extends "base.html" %}
{% load static %}
{% block title %} Zakupoholik.pl {% endblock %}
{% block content %}
    <div class="content">
        <h3>Produkty</h3>
        <ul>
            {% for product in product_with_category %}
                <li class="product_promotion">
                    <div class="left">
                        <img src="{{ product.image_product.url }}" alt="image product">
                    </div>
                    <div class="right">
                        <p id="name_product">{{ product.name_product }}</p>
                        <p id="desc_product">{{ product.descriptions }}</p>
                        <form action="{% url 'shopping_cart:shopping_cart_add' product.id %}" method="post">
                            <span>Ilość:</span>{{ form.amount }}
                            {% csrf_token %}
                            <input type="submit" value="Dodaj">
                        </form>
                    </div>

                </li>
            {% endfor %}
        </ul>

    </div>
{% endblock %}

main/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Zakupoholik.pl {% endblock %}
{% block content %}

    <div class="category_image">
        <ul>
            {% for category in category_product %}
                <li>
                    <a href="{% url 'main:view_for_category' category.slug %}">
                        <div class="image_promotion_category">
                            <i class="{{ category.font_category }}"></i>
                        </div>
                        <div class="description_promotion_category">
                            <p>{{ category.name }}</p>
                        </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="content">
        <h3>Promocje</h3>
        <ul>
            {% for product in all_products_with_promotion %}
                <li class="product_promotion">
                    <div class="left">
                        <img src="{{ product.image_product.url }}" alt="image product">
                    </div>
                    <div class="right">
                        <p id="name_product">{{ product.name_product }}</p>
                        <p id="desc_product">{{ product.descriptions }}</p>
                        <form action="{% url 'shopping_cart:shopping_cart_add' product.id %}" method="post">
                            <span>Ilość:</span>{{ form.amount }}
                            {% csrf_token %}
                            <input type="submit" value="Dodaj">
                        </form>
                    </div>

                </li>
            {% endfor %}
        </ul>

    </div>
{% endblock %}